export const AUTOMATION_CAPABILITIES = {
  available: [
    'local project identity',
    'local collaborative rich-text draft',
    'automatic IndexedDB persistence',
    'Drive-backed project sharing with append-only Yjs merge and local offline persistence',
    'revision-guarded semantic MCP reads and writes',
    'read-only MCP integrity inspection for scenarios, votes, signed vote-event device attestations, annotations, labels, heuristics, and immutable version history',
    'explicit bounded MCP scenario index and one selected turn-revision body readback',
    'dual-revision-guarded MCP creation and restore-as-new-head of immutable policy checkpoints',
    'product version save, restore-as-new-head, and engine-free diff controls',
    'research-revision-guarded MCP scenario creation, turn editing, aggregate voting, annotation lifecycle, and shared labels',
    'product and MCP scenario voting with best-effort registered-device exact-event attribution',
    'product and MCP scenario annotation lifecycle with best-effort registered-device exact-event attribution',
    'product and MCP scenario label lifecycle and assignment changes with best-effort registered-device exact-event attribution',
    'product scenario gallery, editing, voting, and stable-ID scenario links',
    'resumable MCP adversarial review jobs with exact document-source selection, native batch disclosure, cancellation, and no automatic shared mutation',
    'explicit revision-guarded adversarial review archival and immutable human accept/reject history in the shared project',
    'content-minimized authoritative inspection and exact-revision configuration of this installation’s hosted relay approval policy',
  ],
  unavailable: [
    'durable device attribution for research event domains other than scenario votes, annotations, and labels',
    'scenario generation, response evaluation, and spotlight/embed workflows',
    'real-time collaborator presence',
  ],
} as const
